name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    env:
      SHA: ${{ github.sha }}
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        run: docker --version

      # - name: Install Google Cloud SDK
      #   run: |
      #     curl https://sdk.cloud.google.com | bash > /dev/null
      #     source $HOME/google-cloud-sdk/path.bash.inc
      #     gcloud components update kubectl -q

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/473665593474/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: multi-k8s-deployer@multi-k8s-494209.iam.gserviceaccount.com
      
      - name: Check OIDC env
        run: |
          echo "TOKEN: $ACTIONS_ID_TOKEN_REQUEST_TOKEN"
          echo "URL: $ACTIONS_ID_TOKEN_REQUEST_URL"

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Enable GKE auth plugin
        run: echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      - name: Get cluster credentials
        run: gcloud container clusters get-credentials multi-k8s-cluster --zone europe-central2-a

      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      #- name: Build test image
      #  run: docker build -t momir81/react-test -f ./client/Dockerfile.dev ./client

      #- name: Run tests
      #  run: docker run momir81/react-test npm test -- --coverage
      
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: bash ./deploy.sh